server:
  port: 8090

#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: password
#    database-platform: org.hibernate.dialect.H2Dialect

spring:
  application:
    name: spring-reddit-clone
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/batch_db?createDatabaseIfNotExist=true
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  batch:
    initialize-schema: ALWAYS
    job:
      enabled: false

generated:
  output:
    file_path: /
